### ISSUE TITLE
Please add a readme and rest webservice documentation

### ISSUE THREAD

**Issue by mattharrigan** [FizzerWL/WarLight.AI#6]
Thank you for the warlight ai framework.  I have never used C# before and am struggling to get traction.  I would really appreciate a readme, and even better would be some documentation for the webservice at "http://aiserver.warlight.net/api/".  Having the web service is a great way to make it language agnostic but it needs documentation.  My specific goal was to download map details such as territories, connections, and bonuses, but have not had any luck.  Thank you

**Comment by FizzerWL** [comment]
To get map details, use https://www.warlight.net/wiki/Query_game_API with GetHistory=true parameter.
